apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: db-repo
  namespace: app
spec:
  interval: 1m
  url: https://github.com/multi-megaman/cata_sucata_DB
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: db
  namespace: app
spec:
  interval: 1h
  path: ./deploy
  prune: true
  sourceRef:
    kind: GitRepository
    name: db-repo
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
      namespace: flux-system
  postBuild:
    substitute:
      https_repo_url: "https://github.com/multi-megaman/cata_sucata_DB"
