apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: mobile-repo
  namespace: app
spec:
  interval: 1m
  url: https://github.com/multi-megaman/cata_sucata_mobile
  ref:
    branch: main
  secretRef:
    name: flux-system
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mobile
  namespace: app
spec:
  interval: 1h
  path: ./deploy
  prune: true
  sourceRef:
    kind: GitRepository
    name: mobile-repo
