apiVersion: v1
data:
    token: ENC[AES256_GCM,data:TjJX3cXVaDQlq4LvcgmrHvnc8tLqmJxfX8FNxuGPHjYQj0Cwm72fHmXcz3E8cEOZOZ8Z4XyC1+pURAsMdP8xQ4+1Lf7AAIbHaQYsa/hn1aTF06SfSRV/DXttCTZL,iv:pI2Z7V6e4LchVzhJP0asbPwwgQf5+deUZEP5Dov+bA8=,tag:FzEH0ndAfe6xJayKwMkJNw==,type:str]
kind: Secret
metadata:
    name: model-github-api-token
sops:
    lastmodified: "2025-07-06T13:36:20Z"
    mac: ENC[AES256_GCM,data:u6naC9Ak1lcO3j7b2SKBZW32Wa39Fuct3w1AHIZk2pgcNNFRDPlyWSyts5yHppbAGeACBqivED0mIMkBrq4G9GNjhwlULp0cQO6vbUqKRn2jWnQE40aS9GS6rt1T1+hABIUzgZpbpf6tXUnxPlQbEszc0A/0G6KEvk5DXhB/gM8=,iv:cbEeYPFKLoCNLM/38nPMuwd6NrTGyF0xe9zcacgg+Nc=,tag:1v3k4dL5wWgmVBH6SDwJAQ==,type:str]
    pgp:
        - created_at: "2025-07-06T13:36:20Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/4yvwOA2tSbAQ/7BnFdBLnOxhYxXee3JrGaSwLRbi8jKu/yOTOYHrdm+9+h
            COF9uparytAGxfaOs2Tnd+vkzs+BUGqBZWW/SUN4F5nO9QiPXY9QBuf8KJeeYPey
            SgodrGJpAFNBeCcT2C/rTDXN5qNlCUe6Zn/JcAev/8FBTrtJp7GdJpRcjcIGv20Y
            OhH839+eumM6dWEhtg5Dt2nPUkZ9JpiJG6oG27Qxn+qaNOT9cpk/8swOIPWPg2nJ
            lxm4c2/dlt3XjonU1owET92+Tb8kzAqdILr3DsLIjtn9JafMbYHjmc1/TwGOTtRf
            WwGXvui4dA9Gz6m7jv/QNxet6nkb6R0DAegQY2filukilFMVDhjTkRaO4TI/o+IU
            XvwWHSgoD4BsCZdbcIMXT+ay5ePeQP8Yuz7wkPZk8R82co1mX8fjHJ3Sna4IgtxE
            6eCwJ9XkQwI5Y53B8F5f+V1I76CuvB06LBn2BYCu3UmAwTSv4SGem1jIaTkdZW3Z
            76HGM/jl+F8UnsrWfIcw1SV/bIwOnSylIvKj1HBbsnrQiWPhovoC4rE6PdZCJkWq
            3cF+oRpa2SkFLka+n7ww9QmaifJpEiBg0+5do1Zxc3d1m66RmhAurf3nBBUjGG/l
            cRNXNrdYYUJXJO5jXbT34Wh0zxPokGmIeAoRd6Rv6qGyhLJppw8m9iBNtOA/XybS
            XgGn6ivjjz1FyEa2ux/DJV7vAJ+VUCvRhzYZ6yQnlkndEVSlpH9IzRunWD+Mk2Ae
            hDqRfRU0bduxx+uUeNnRFeRzhIAmHFzI5Nh3QGqCEpO1D/laK8yaR9QrPjQ5Pns=
            =wu+B
            -----END PGP MESSAGE-----
          fp: 5E634DB1649398A41244F0E66C9BB1C17F421C5A
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
